name             'rb-common'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Redborder common system settings'
version          '0.0.1'
